### ISSUE TITLE
Would like to contribute if you are accepting contributions

### ISSUE THREAD

**Issue by StandinKP** [basalt-org/basalt#42]

**Comment by StijnWoestenborghs** [comment]
@StandinKP Absolutely! We are opening up the project for contributions. Currently drafting the contributor guide and an appropriate README. In the mean time, feel free to open a PR and share your thoughts.

**Comment by StandinKP** [comment]
Great. Do we have some plan what are we developing currently or some roadmap we are following? So I can take up some feature and put up a PR

**Comment by StijnWoestenborghs** [comment]
There is. (Also in the progress of opening now) I can tell you that currently some of the features include:
- Tensor slicing
- Operators: Slice, (Un)Squeeze, Concat, Clip, Gather, Split, FMA ... 
- Initializers
- Graph submodules & concatenation (model + loss) 
...

**Comment by StandinKP** [comment]
Great. Thanks
