### ISSUE TITLE
Mojopkg gh action

### ISSUE THREAD

**Issue by Moosems** [basalt-org/basalt#46]
I could create some GH actions to Stu run the tests and make mojopkg files for release :)

**Comment by StijnWoestenborghs** [comment]
Hi @Moosems, I think it is just a little too early for that. For sure this is definitely needed at some point. But API's, test layout and packaging/distributing itself will change a lot in the near future, so I'm afraid maintaining the gh action will become a hassle on itself for now. Keep it in mind for some of the next versions though!

**Comment by Moosems** [comment]
Thanks for the quick reply! I only asked because I created a script for one of my older projects and it's very easy to adapt for most projects and doesn't require much upkeep so I've been going around offering it to different projects I've been watching :) Hope you have a great day!
