### ISSUE TITLE
Debugging examples

### ISSUE THREAD

**Issue by obadakhalili** [basalt-org/basalt#47]
I don't think this is the best place to ask for help on this, but ...

I want to debug the file `./examples/housing.mojo` that imports the package `./basalt`. When I try to debug the file with Mojo's VSCode debugger, I get the error message `unable to locate module 'basalt'`, the same error message that throws if I try to run `./examples/housing.mojo` without setting the path argument (`-I`), so it seems like the problem is that I have to specify the path argument for the debugger too. I tried to update the launch file configuration by setting the `args` property to `["-I", "../"]` (I have also tried `"."` and `"./basalt"`), which does show up in the final command but still doesn't work, throwing the same error message.

So my question is how to set up the correct debugging profile to debug the `basalt` package in Mojo.

**Comment by StijnWoestenborghs** [comment]
Interesting, I haven't been using the vscode debugger so far. I guess what you can do as a quick fix is temporarily move the `./examples/housing.mojo` to the root of the directory. But I'll have a better look on how to solve it properly

**Comment by obadakhalili** [comment]
What have you been using?

**Comment by StijnWoestenborghs** [comment]
People might shoot me for this: But personally a fan of developing features against unit-tests and small POCs with print statements, before integrating it. And inside `basalt/nn/model.mojo` there is a nice performance feature implemented by @andresnowak that allows you to evaluate the performance on forward and backward pass of each individual op.

![image](https://github.com/basalt-org/basalt/assets/46826967/c1bb933d-5d54-4a89-9d4c-d30c5bf406e4)

Using it properly is also suffering from the include arg `-I .` So there might be a argument for finding a different solution at all

**Comment by obadakhalili** [comment]
> personally a fan of developing features against unit-tests and small POCs with print statements

Yeah, that's fine, Though for my purposes, learning Mojo and Basalt, a debugger is more suitable.

For now, I will be trying the option to move the file.
